# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engmt < Formula
  desc "Engineering Management Platform - Single binary with embedded frontend and database"
  homepage "https://github.com/hweeks/engmt"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hweeks/engmt/releases/download/v0.3.0/engmt_Darwin_x86_64.tar.gz"
    sha256 "32876dd44c32b1087d71523090e52ec180ab437b97b1e78ad4c5e6f0350843ee"

    def install
      bin.install "engmt"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hweeks/engmt/releases/download/v0.3.0/engmt_Darwin_arm64.tar.gz"
    sha256 "ce7c03525fc70bbc8d559bbbb00c58117bfdd6bca01058fee8cae8ae259a66f0"

    def install
      bin.install "engmt"
    end
  end

  test do
    system "#{bin}/engmt", "--help"
  end
end
