# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engmt < Formula
  desc "Engineering Management Platform - Single binary with embedded frontend and database"
  homepage "https://github.com/hweeks/engmt"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hweeks/engmt/releases/download/v0.1.0/engmt_Darwin_x86_64.tar.gz"
    sha256 "578d22bd5e48e6825f87d6930feca3b36b4294990014089d651c83ab203347af"

    def install
      bin.install "engmt"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hweeks/engmt/releases/download/v0.1.0/engmt_Darwin_arm64.tar.gz"
    sha256 "0e866c75e4b64ae54fd1820af4ae7a9186760d01c985fac57024ce4524743ff0"

    def install
      bin.install "engmt"
    end
  end

  test do
    system "#{bin}/engmt", "--help"
  end
end
